CREATE TYPE "base_user_type" AS ENUM (
  'ADMIN',
  'BOOKDROP_USER',
  'USER'
);

CREATE TYPE "pricing_plan" AS ENUM (
  'FREE',
  'PREMIUM'
);

CREATE TYPE "books_extension" AS ENUM (
  'SHORT',
  'MEDIUM',
  'LONG'
);

CREATE TYPE "cover_type" AS ENUM (
  'HARDCOVER',
  'PAPERBACK'
);

CREATE TYPE "book_condition" AS ENUM (
  'LIKE_NEW',
  'VERY_GOOD',
  'GOOD',
  'ACCEPTABLE',
  'POOR'
);

CREATE TYPE "book_status" AS ENUM (
  'PUBLISHED',
  'DRAFT',
  'PAUSED',
  'RESERVED',
  'EXCHANGED',
  'DELETED'
);

CREATE TYPE "swipe_direction" AS ENUM (
  'LEFT',
  'RIGHT'
);

CREATE TYPE "match_status" AS ENUM (
  'NEW',
  'CHAT_CREATED'
);

CREATE TYPE "chat_type" AS ENUM (
  'EXCHANGE',
  'COMMUNITY'
);

CREATE TYPE "exchange_status" AS ENUM (
  'NEGOTIATING',
  'ACCEPTED_BY_1',
  'ACCEPTED_BY_2',
  'ACCEPTED',
  'REJECTED',
  'COMPLETED',
  'INCIDENT'
);

CREATE TYPE "exchange_mode" AS ENUM (
  'BOOKSPOT',
  'BOOKDROP',
  'CUSTOM'
);

CREATE TYPE "exchange_meeting_status" AS ENUM (
  'PROPOSAL',
  'ACCEPTED',
  'REFUSED'
);

CREATE TYPE "bookspot_status" AS ENUM (
  'PENDING',
  'ACTIVE',
  'REJECTED'
);

CREATE TYPE "community_status" AS ENUM (
  'CREATED',
  'ACTIVE',
  'ARCHIVED'
);

CREATE TYPE "community_role" AS ENUM (
  'MEMBER',
  'MODERATOR'
);

CREATE TYPE "meetup_status" AS ENUM (
  'SCHEDULED',
  'CELEBRATED',
  'CANCELLED'
);

CREATE TYPE "meetup_attendance_status" AS ENUM (
  'REGISTERED',
  'ATTENDED',
  'NO_SHOW',
  'CANCELLED'
);

CREATE TYPE "points_ledger_type" AS ENUM (
  'EXCHANGE_SUCCESS',
  'MEETUP_ATTENDANCE',
  'PURCHASE',
  'LOGIN_STREAK',
  'ADJUSTMENT'
);

CREATE TYPE "incident_status" AS ENUM (
  'PENDING',
  'REVISED',
  'DESESTIMATED'
);

CREATE TABLE "base_users" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "supabase_id" text UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "foto_perfil_url" varchar,
  "type" int NOT NULL,
  "location" geography(Point,4326) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "admins" (
  "id" UUID PRIMARY KEY
);

CREATE TABLE "bookdrop_users" (
  "id" UUID PRIMARY KEY,
  "book_spot_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" UUID PRIMARY KEY,
  "rating_mean" decimal NOT NULL DEFAULT 0,
  "finished_exchanges" int NOT NULL DEFAULT 0,
  "plan" pricing_plan NOT NULL DEFAULT 'FREE'
);

CREATE TABLE "user_preferences" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" UUID UNIQUE NOT NULL,
  "location" geography(Point,4326) NOT NULL,
  "radio_km" int NOT NULL,
  "extension" books_extension NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "genres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "user_preferences_genres" (
  "preferences_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("preferences_id", "genre_id")
);

CREATE TABLE "books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" UUID NOT NULL,
  "isbn" varchar,
  "titulo" varchar,
  "autor" varchar,
  "editorial" varchar,
  "num_paginas" int,
  "cover" cover_type,
  "condition" book_condition,
  "observaciones" text,
  "status" book_status NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "languages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language" varchar UNIQUE NOT NULL
);

CREATE TABLE "books_languages" (
  "book_id" int NOT NULL,
  "language_id" int NOT NULL,
  PRIMARY KEY ("book_id", "language_id")
);

CREATE TABLE "books_genres" (
  "book_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("book_id", "genre_id")
);

CREATE TABLE "book_photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" int NOT NULL,
  "url" varchar NOT NULL,
  "orden" int NOT NULL DEFAULT 0
);

CREATE TABLE "swipes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "swiper_id" UUID NOT NULL,
  "book_id" int NOT NULL,
  "direction" swipe_direction NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" UUID NOT NULL,
  "user2_id" UUID NOT NULL,
  "book1_id" int NOT NULL,
  "book2_id" int NOT NULL,
  "status" match_status NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "chats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" chat_type NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "chat_participants" (
  "chat_id" int NOT NULL,
  "user_id" UUID NOT NULL,
  "joined_at" timestamp NOT NULL,
  PRIMARY KEY ("chat_id", "user_id")
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int NOT NULL,
  "sender_id" UUID NOT NULL,
  "body" text NOT NULL,
  "sent_at" timestamp NOT NULL
);

CREATE TABLE "exchanges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int UNIQUE NOT NULL,
  "match_id" int NOT NULL,
  "status" exchange_status NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "exchange_meetings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exchange_id" int UNIQUE NOT NULL,
  "mode" exchange_mode NOT NULL,
  "bookspot_id" int,
  "custom_location" geography(Point,4326) NULL,
  "scheduled_at" timestamp,
  "proposer_id" UUID NOT NULL,
  "status" exchange_meeting_status NOT NULL,
  "mark_as_completed_by_user1" boolean DEFAULT false,
  "mark_as_completed_by_user2" boolean DEFAULT false
);

CREATE TABLE "bookspots" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "address_text" varchar,
  "location" geography(Point,4326) NOT NULL,
  "is_bookdrop" boolean NOT NULL DEFAULT false,
  "created_by_user_id" UUID,
  "owner_id" UUID,
  "status" bookspot_status NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "bookspot_validations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bookspot_id" int NOT NULL,
  "validator_user_id" UUID NOT NULL,
  "knows_place" boolean NOT NULL DEFAULT false,
  "safe_for_exchange" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "communities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "reference_bookspot_id" int NOT NULL,
  "status" community_status NOT NULL,
  "creator_id" UUID NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "community_members" (
  "community_id" int NOT NULL,
  "user_id" UUID NOT NULL,
  "role" community_role NOT NULL,
  "joined_at" timestamp NOT NULL,
  PRIMARY KEY ("community_id", "user_id")
);

CREATE TABLE "community_chats" (
  "community_id" int UNIQUE NOT NULL,
  "chat_id" int UNIQUE NOT NULL,
  PRIMARY KEY ("community_id", "chat_id")
);

CREATE TABLE "community_library_likes" (
  "community_id" int NOT NULL,
  "user_id" UUID NOT NULL,
  "book_id" int NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("community_id", "user_id", "book_id")
);

CREATE TABLE "meetups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "community_id" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "other_book_spot_id" int,
  "other_location" geography(Point,4326),
  "scheduled_at" timestamp NOT NULL,
  "status" meetup_status NOT NULL,
  "creator_id" UUID NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "meetup_attendance" (
  "meetup_id" int NOT NULL,
  "user_id" UUID NOT NULL,
  "selected_book_id" int NOT NULL,
  "status" meetup_attendance_status NOT NULL,
  PRIMARY KEY ("meetup_id", "user_id")
);

CREATE TABLE "points_ledgers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" UUID NOT NULL,
  "type" points_ledger_type NOT NULL,
  "amount" int NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "user_progress" (
  "user_id" UUID PRIMARY KEY,
  "xp_total" int NOT NULL DEFAULT 0,
  "streak_weeks" int NOT NULL DEFAULT 0,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "community_monthly_scores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "community_id" int NOT NULL,
  "user_id" UUID NOT NULL,
  "month" varchar NOT NULL,
  "inkdrops_this_month" int NOT NULL DEFAULT 0
);

CREATE TABLE "incidents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exchange_id" int NOT NULL,
  "meetup_id" int NOT NULL,
  "informer_id" UUID NOT NULL,
  "informed_id" UUID NOT NULL,
  "admin_id" UUID NOT NULL,
  "comment" text NOT NULL,
  "status" incident_status NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE UNIQUE INDEX ON "swipes" ("swiper_id", "book_id");

CREATE UNIQUE INDEX ON "bookspot_validations" ("bookspot_id", "validator_user_id");

CREATE UNIQUE INDEX ON "community_monthly_scores" ("community_id", "user_id", "month");

COMMENT ON COLUMN "matches"."user1_id" IS 'first interested user';

COMMENT ON COLUMN "matches"."user2_id" IS 'second interested user';

COMMENT ON COLUMN "exchanges"."chat_id" IS '1 chat = 1 exchange';

COMMENT ON COLUMN "community_monthly_scores"."month" IS 'YYYY-MM';

COMMENT ON COLUMN "incidents"."informer_id" IS 'usuario que pone la indicendia';

COMMENT ON COLUMN "incidents"."informed_id" IS 'usuario sobre el que se pone la incidencia';

ALTER TABLE base_users ADD COLUMN IF NOT EXISTS password_hash text;

ALTER TABLE "admins" ADD FOREIGN KEY ("id") REFERENCES "base_users" ("id");

ALTER TABLE "bookdrop_users" ADD FOREIGN KEY ("id") REFERENCES "base_users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "base_users" ("id");

ALTER TABLE "user_preferences" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_preferences_genres" ADD FOREIGN KEY ("preferences_id") REFERENCES "user_preferences" ("id");

ALTER TABLE "user_preferences_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "books" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "books_languages" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_languages" ADD FOREIGN KEY ("language_id") REFERENCES "languages" ("id");

ALTER TABLE "books_genres" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "book_photos" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "swipes" ADD FOREIGN KEY ("swiper_id") REFERENCES "users" ("id");

ALTER TABLE "swipes" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("book1_id") REFERENCES "books" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("book2_id") REFERENCES "books" ("id");

ALTER TABLE "chat_participants" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "chat_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "exchanges" ADD FOREIGN KEY ("match_id") REFERENCES "matches" ("id");

ALTER TABLE "exchange_meetings" ADD FOREIGN KEY ("exchange_id") REFERENCES "exchanges" ("id");

ALTER TABLE "exchange_meetings" ADD FOREIGN KEY ("bookspot_id") REFERENCES "bookspots" ("id");

ALTER TABLE "exchange_meetings" ADD FOREIGN KEY ("proposer_id") REFERENCES "users" ("id");

ALTER TABLE "bookspots" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "bookspots" ADD FOREIGN KEY ("owner_id") REFERENCES "bookdrop_users" ("id");

ALTER TABLE "bookspot_validations" ADD FOREIGN KEY ("bookspot_id") REFERENCES "bookspots" ("id");

ALTER TABLE "bookspot_validations" ADD FOREIGN KEY ("validator_user_id") REFERENCES "users" ("id");

ALTER TABLE "communities" ADD FOREIGN KEY ("reference_bookspot_id") REFERENCES "bookspots" ("id");

ALTER TABLE "communities" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "community_members" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "community_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "community_chats" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "community_chats" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "community_library_likes" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "community_library_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "community_library_likes" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "meetups" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "meetups" ADD FOREIGN KEY ("other_book_spot_id") REFERENCES "bookspots" ("id");

ALTER TABLE "meetups" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "meetup_attendance" ADD FOREIGN KEY ("meetup_id") REFERENCES "meetups" ("id");

ALTER TABLE "meetup_attendance" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "meetup_attendance" ADD FOREIGN KEY ("selected_book_id") REFERENCES "books" ("id");

ALTER TABLE "points_ledgers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "community_monthly_scores" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "community_monthly_scores" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "incidents" ADD FOREIGN KEY ("exchange_id") REFERENCES "exchanges" ("id");

ALTER TABLE "incidents" ADD FOREIGN KEY ("meetup_id") REFERENCES "meetups" ("id");

ALTER TABLE "incidents" ADD FOREIGN KEY ("informer_id") REFERENCES "users" ("id");

ALTER TABLE "incidents" ADD FOREIGN KEY ("informed_id") REFERENCES "users" ("id");

ALTER TABLE "incidents" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("id");